apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: prod
  template:
    metadata:
      name: "app-{{.env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
    spec:
      project: k3s-environments
      source:
        repoURL: https://github.com/leogues/k3s-gitops.git
        targetRevision: HEAD
        path: envs/{{.env}}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true